version: '3.8'

services:
  api:
    build: .
    container_name: credit_risk_api
    ports:
      - "8000:8000"
    volumes:
      # Mount mlruns so the container can see the local trained models
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns